In [3]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [6]:
percentage = 100*A/cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [10]:
B = np.array([[1], [2], [3], [4]])
print(B+100)

[[101]
 [102]
 [103]
 [104]]


In [11]:
C = np.array([[1,2,3],[4,5,6]])
D = np.array([100,200,300])
print(C+D)

[[101 202 303]
 [104 205 306]]


(m,n) matrix operated with (1,n) matrix converts (1,n) to (m,n) and then performs operation. (m,1) matrix operated with (m,n) converts (m,1) to (m,n) and performs operations. Broadcasting can help simplify code.