In [1]:
import numpy as np

a = np.random.randn(5)

In [3]:
print(a)

[-0.51933038  0.65218074 -0.49305645  0.59511654  0.42101774]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[-0.51933038  0.65218074 -0.49305645  0.59511654  0.42101774]


In [6]:
print(np.dot(a,a.T))

1.4695680582587123


In [11]:
b = np.random.randn(5,1)
print(b)

[[-0.93933424]
 [ 0.12652843]
 [-1.817037  ]
 [ 0.14160808]
 [-0.01165788]]


In [12]:
print(b.T)

[[-0.93933424  0.12652843 -1.817037    0.14160808 -0.01165788]]


In [13]:
print(np.dot(b,b.T))

[[ 8.82348810e-01 -1.18852487e-01  1.70680507e+00 -1.33017322e-01
   1.09506445e-02]
 [-1.18852487e-01  1.60094437e-02 -2.29906840e-01  1.79174486e-02
  -1.47505308e-03]
 [ 1.70680507e+00 -2.29906840e-01  3.30162347e+00 -2.57307129e-01
   2.11827967e-02]
 [-1.33017322e-01  1.79174486e-02 -2.57307129e-01  2.00528495e-02
  -1.65084985e-03]
 [ 1.09506445e-02 -1.47505308e-03  2.11827967e-02 -1.65084985e-03
   1.35906133e-04]]


Do not use rank-1 arrays. Instead, commit to making it a column or row vector by specifying second dimension.

In [15]:
assert(b.shape==(5,1))

assert statements serve as good documentation and help protect against these errors.

In [16]:
a = a.reshape(5,1)

In [17]:
assert(a.shape==(5,1))

Use reshape command to fix previously rank-1 vectors.